before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch: 
      - arm
    goarm: 
      - 7
archives:
 -  format: binary
    name_template: "{{ .Binary }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
